VideoRecorder-DotNetCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace VideoRecorder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
    }
}

VideoRecorder-DotNetCore/Controllers/VideoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace VideoRecorder.Controllers
{    
    public class VideoController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SaveRecoredFile()
        {
            if( Request.Form.Files.Any())
            {
                try
                {
                    var file = Request.Form.Files["video-blob"];
                    string UploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadedFiles");
                    string UniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName + ".webm";
                    string UploadPath = Path.Combine(UploadFolder, UniqueFileName);
                    await file.CopyToAsync(new FileStream(UploadPath, FileMode.Create));                    
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }
            }           
            return Json(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult DeleteFile()
        {
            var fileUrl = AppDomain.CurrentDomain.BaseDirectory + "UploadedFiles/" + Request.Form["delete-file"] + ".webm";
            new FileInfo(fileUrl).Delete();
            return Json(true);
        }
    }
}

VideoRecorder-DotNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="container">
    <h2>ASP.NET Core Sample</h2>
    <p>A collection of ASP.NET Core Sample programs</p>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Code Example</th>
                <th>Link</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>          
            <tr>
                <td>Record Audio/Video</td>
                <td><a asp-area="" asp-controller="Video" asp-action="Index">Click Here</a></td>
                <td>Record Audio/Video using .Net Core MVC</td>
            </tr>
        </tbody>
    </table>
</div>

VideoRecorder-DotNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoRecorder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Video.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VideoRecorder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - VideoRecorder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
    <script src="~/js/Video.js" asp-append-version="true" async></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true" ></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

VideoRecorder-DotNetCore/Views/Video/Index.cshtml
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="container">

	<h1>
		<a href="//webrtc.github.io/samples/" title="WebRTC samples homepage">WebRTC Asp.Net Core</a>
		<span>Audio/Video Recording</span>
	</h1>

	@*<p>
		For more information see the MediaStream Recording API <a href="http://w3c.github.io/mediacapture-record/MediaRecorder.html"
																  title="W3C MediaStream Recording API Editor's Draft">Editor's&nbsp;Draft</a>.
	</p>*@

	<video id="gum" playsinline autoplay muted style="border: 1px solid rgb(15, 158, 238); height: 240px; width: 320px;" ></video>
	<video id="recorded" playsinline loop style="border: 1px solid rgb(15, 158, 238); height: 240px; width: 320px; display:none;"></video>

	<div>
		<button id="start" class="btn btn-success" style="display:none">Start camera</button>
		<button id="record" class="btn btn-info">Start Recording</button>
		<button id="download" disabled class="btn btn-dark">Upload</button>
		<button id="stop" class="btn btn-danger" style="display:none">Stop camera</button>
	</div>

	<div>
		Recording format: <select id="codecPreferences" disabled></select>
	</div>

	<div>
		<h4>Media Stream Constraints options</h4>
		<p>Echo cancellation: <input type="checkbox" id="echoCancellation"></p>
	</div>

	<div>
		<span id="errorMsg"></span>
	</div>

</div>